- name: Make DNS lookup
  template:
    src: resolv.conf
    dest: "/etc/resolv.conf"

- name: Disable systemd-resolved
  become: yes
  command: systemctl disable systemd-resolved.service

- meta: flush_handlers

- name: install dnsmasq
  apt: name=dnsmasq state=present

- name: "setup"
  template:
    src: main.conf
    dest: "/etc/dnsmasq.d/main.conf"
  notify: restart dnsmasq